# Generated by Django 6.0.6 on 2026-08-23 20:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laboratory', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LaboratoryTestParameter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=50)),
                ('unit', models.CharField(blank=True, max_length=50)),
                ('data_type', models.CharField(default='text', max_length=20)),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='parameters', to='laboratory.laboratorytest')),
            ],
        ),
    ]
