# Generated by Django 6.0.6 on 2026-08-24 17:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laboratory', '0002_laboratorytestparameter'),
    ]

    operations = [
        migrations.CreateModel(
            name='LaboratoryResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='results', to='laboratory.laboratoryorderitem')),
                ('parameter', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='results', to='laboratory.laboratorytestparameter')),
            ],
        ),
    ]
