# Generated by Django 6.0.6 on 2026-08-28 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laboratory', '0003_laboratoryresult'),
    ]

    operations = [
        migrations.AlterField(
            model_name='laboratoryorderitem',
            name='status',
            field=models.CharField(choices=[('ordered', 'Ordered'), ('collected', 'Sample Collected'), ('verified', 'Verified'), ('released', 'Released'), ('cancelled', 'Cancelled')], default='ordered', max_length=20),
        ),
    ]
