# Generated by Django 6.0.6 on 2026-09-02 06:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laboratory', '0004_alter_laboratoryorderitem_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Container',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='SpecimenType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='SpecimenRequirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_preferred', models.BooleanField(default=False)),
                ('collection_instructions', models.TextField(blank=True)),
                ('container', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='test_requirements', to='laboratory.container')),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='specimen_requirements', to='laboratory.laboratorytest')),
                ('specimen_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='test_requirements', to='laboratory.specimentype')),
            ],
        ),
    ]
