# Generated by Django 6.0.6 on 2026-09-02 11:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laboratory', '0005_container_specimentype_specimenrequirement'),
        ('visits', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Specimen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('specimen_number', models.CharField(max_length=50, unique=True)),
                ('status', models.CharField(default='collected', max_length=30)),
                ('collected_at', models.DateTimeField()),
                ('received_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True)),
                ('volume', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('volume_unit', models.CharField(blank=True, max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('container', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='specimens', to='laboratory.container')),
                ('specimen_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='specimens', to='laboratory.specimentype')),
                ('visit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='specimens', to='visits.visit')),
            ],
        ),
    ]
