# Generated by Django 6.0.6 on 2026-09-02 12:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laboratory', '0006_specimen'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpecimenAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('order_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='specimen_assignments', to='laboratory.laboratoryorderitem')),
                ('specimen', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assignments', to='laboratory.specimen')),
            ],
        ),
    ]
