# Generated by Django 6.0.6 on 2026-09-03 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laboratory', '0007_specimenassignment'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='specimenassignment',
            constraint=models.UniqueConstraint(fields=('specimen', 'order_item'), name='unique_specimen_order_item_assignment'),
        ),
    ]
