# Generated by Django 6.0.6 on 2026-09-04 19:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laboratory', '0008_specimenassignment_unique_specimen_order_item_assignment'),
    ]

    operations = [
        migrations.AddField(
            model_name='specimenassignment',
            name='requirement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='assignments', to='laboratory.specimenrequirement'),
        ),
    ]
