# Generated by Django 6.0.6 on 2026-09-05 17:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laboratory', '0009_specimenassignment_requirement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='specimenassignment',
            name='requirement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assignments', to='laboratory.specimenrequirement'),
        ),
    ]
