# Generated by Django 6.0.6 on 2026-09-05 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laboratory', '0010_alter_specimenassignment_requirement'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='specimenrequirement',
            constraint=models.UniqueConstraint(fields=('test', 'specimen_type', 'container'), name='unique_test_specimen_type_container_requirement'),
        ),
    ]
