# Generated by Django 6.0.6 on 2026-09-05 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laboratory', '0011_specimenrequirement_unique_test_specimen_type_container_requirement'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='specimenrequirement',
            constraint=models.UniqueConstraint(condition=models.Q(('is_preferred', True)), fields=('test',), name='unique_preferred_specimen_requirement_per_test'),
        ),
    ]
