# Generated by Django 6.0.6 on 2026-09-15 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laboratory', '0012_specimenrequirement_unique_preferred_specimen_requirement_per_test'),
    ]

    operations = [
        migrations.AddField(
            model_name='specimenassignment',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
