# Generated by Django 6.0.6 on 2026-09-15 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laboratory', '0013_specimenassignment_is_active'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='specimenassignment',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('order_item',), name='unique_active_specimen_assignment_per_order_item'),
        ),
    ]
