# Generated by Django 6.0.6 on 2026-09-26 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laboratory', '0014_specimenassignment_unique_active_specimen_assignment_per_order_item'),
    ]

    operations = [
        migrations.AlterField(
            model_name='specimen',
            name='status',
            field=models.CharField(choices=[('collected', 'Collected'), ('received', 'Received'), ('rejected', 'Rejected')], default='collected', max_length=20),
        ),
    ]
