# Generated by Django 6.0.6 on 2026-09-28 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laboratory', '0015_alter_specimen_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='laboratoryorderitem',
            name='status',
            field=models.CharField(choices=[('ordered', 'Ordered'), ('collected', 'Sample Collected'), ('results_in_progress', 'Results In Progress'), ('ready_for_verification', 'Ready for Verification'), ('verified', 'Verified'), ('released', 'Released'), ('cancelled', 'Cancelled')], default='ordered', max_length=30),
        ),
    ]
